#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Dec 17 00:25:43 +0800 2022
# SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
#
# Tool Version Limit: 2022.04 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xlconcat_v2_1_4 xil_defaultlib axis_infrastructure_v1_1_0 axis_register_slice_v1_1_26 axis_subset_converter_v1_1_26 xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 floating_point_v7_0_20 xbip_dsp48_mult_v3_0_6 xbip_dsp48_multadd_v3_0_6 div_gen_v5_1_19 v_frmbuf_wr_v2_4_0 v_frmbuf_rd_v2_4_0 axi_lite_ipif_v3_0_4 axi_intc_v4_1_17 lib_pkg_v1_0_2 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_iic_v2_1_2 axi_infrastructure_v1_1_0 axi_vip_v1_1_12 zynq_ultra_ps_e_vip_v1_0_12 axi_gpio_v2_0_28 xlslice_v1_0_2 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_26 fifo_generator_v13_2_7 axi_data_fifo_v2_1_25 axi_crossbar_v2_1_27 proc_sys_reset_v5_0_13 xlconstant_v1_1_7 smartconnect_v1_0 axi_protocol_converter_v2_1_26 axi_clock_converter_v2_1_25 blk_mem_gen_v8_4_5 axi_dwidth_converter_v2_1_26)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2022.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/aca3/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tdata_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tuser_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tstrb_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tkeep_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tid_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tdest_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tlast_design_1_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/1676/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/top_design_1_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/sim/design_1_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_18 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ab19/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_20 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/1b8e/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_mult_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/490d/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work div_gen_v5_1_19 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/163a/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_frmbuf_wr_v2_4_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/3984/hdl/v_frmbuf_wr_v2_4_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_frmbuf_wr_0_0/sim/design_1_v_frmbuf_wr_0_0.v" \
    "$ref_dir/../../../bd/design_1/ipshared/6a38/hdl/csi2_rx_to_pixel.v" \
    "$ref_dir/../../../bd/design_1/ipshared/6a38/hdl/dphy_rx_to_byte.v" \
    "$ref_dir/../../../bd/design_1/ipshared/6a38/hdl/mipi_rx_to_video.v" \
    "$ref_dir/../../../bd/design_1/ipshared/6a38/hdl/mipi_rx_to_video_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/design_1/ipshared/6a38/hdl/mipi_rx_to_video_v1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_rx_to_video_0_0/sim/design_1_mipi_rx_to_video_0_0.v" \
    "$ref_dir/../../../bd/design_1/ipshared/xil_isp_lite_1.0/hdl/isp_lite/isp_utils.v" \
    "$ref_dir/../../../bd/design_1/ipshared/8829/hdl/video_to_axis.v" \
    "$ref_dir/../../../bd/design_1/ipshared/8829/hdl/video_to_axis_v1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_video_to_axis_0_0/sim/design_1_video_to_axis_0_0.v" \
    "$ref_dir/../../../bd/design_1/ipshared/2133/hdl/axis_to_video.v" \
    "$ref_dir/../../../bd/design_1/ipshared/2133/hdl/video_timing_gen.v" \
    "$ref_dir/../../../bd/design_1/ipshared/2133/hdl/axis_to_video_v1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_to_video_0_0/sim/design_1_axis_to_video_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_frmbuf_rd_v2_4_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_rd_0_0/hdl/v_frmbuf_rd_v2_4_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_frmbuf_rd_0_0/sim/design_1_v_frmbuf_rd_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_frmbuf_wr_0_1/sim/design_1_v_frmbuf_wr_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_video_to_axis_1_0/sim/design_1_video_to_axis_1_0.v" \
    "$ref_dir/../../../bd/design_1/ipshared/3450/hdl/vip/vip_crop.v" \
    "$ref_dir/../../../bd/design_1/ipshared/3450/hdl/vip/vip_dscale.v" \
    "$ref_dir/../../../bd/design_1/ipshared/3450/hdl/vip/vip_hist_equ.v" \
    "$ref_dir/../../../bd/design_1/ipshared/3450/hdl/vip/vip_osd.v" \
    "$ref_dir/../../../bd/design_1/ipshared/3450/hdl/vip/vip_sobel.v" \
    "$ref_dir/../../../bd/design_1/ipshared/3450/hdl/vip/vip_top.v" \
    "$ref_dir/../../../bd/design_1/ipshared/3450/hdl/vip/vip_yuv2rgb.v" \
    "$ref_dir/../../../bd/design_1/ipshared/3450/hdl/vip/vip_yuv444to422.v" \
    "$ref_dir/../../../bd/design_1/ipshared/3450/hdl/xil_vip_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/design_1/ipshared/3450/hdl/xil_vip_v1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xil_vip_0_0/sim/design_1_xil_vip_0_0.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_2dnr.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_blc.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_bnr.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_ccm.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_csc.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_demosaic.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_dgain.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_dpc.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_ee.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_gamma.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_stat_ae.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_stat_awb.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_top.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/isp_lite/isp_wb.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/xil_isp_lite_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/design_1/ipshared/f095/hdl/xil_isp_lite_v1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xil_isp_lite_0_0/sim/design_1_xil_isp_lite_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_2/hdl/tdata_design_1_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_2/hdl/tuser_design_1_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_2/hdl/tstrb_design_1_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_2/hdl/tkeep_design_1_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_2/hdl/tid_design_1_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_2/hdl/tdest_design_1_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_2/hdl/tlast_design_1_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_2/hdl/top_design_1_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_subset_converter_0_2/sim/design_1_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_frm_wr_0_0/sim/design_1_v_frm_wr_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mipi_rx_to_video_ias1_0/sim/design_1_mipi_rx_to_video_ias1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_video_to_axis_0_1/sim/design_1_video_to_axis_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_17 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/802b/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_intc_0_0/sim/design_1_axi_intc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_1_2 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/eddf/hdl/axi_iic_v2_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_iic_0_0/sim/design_1_axi_iic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/1033/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_gpio_v2_0_28 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/3ed9/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_0/sim/design_1_xlslice_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_1_0/sim/design_1_xlslice_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_2_0/sim/design_1_xlslice_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_3_0/sim/design_1_xlslice_3_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_4_0/sim/design_1_xlslice_4_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xil_vip_0_1/sim/design_1_xil_vip_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_video_to_axis_0_2/sim/design_1_video_to_axis_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_v_frmbuf_wr_0_2/sim/design_1_v_frmbuf_wr_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_4_1/sim/design_1_xlslice_4_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_5_0/sim/design_1_xlslice_5_0.v" \
    "$ref_dir/d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_vcu_0_0/design_1_vcu_0_0_sim_netlist.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/0a3f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/5390/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/3fa0/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_clk_wiz_99M_0/sim/design_1_rst_clk_wiz_99M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_0/sim/bd_6f02_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/sim/bd_6f02_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_2/sim/bd_6f02_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_3/sim/bd_6f02_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_4/sim/bd_6f02_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/sim/bd_6f02_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/sim/bd_6f02_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/sim/bd_6f02_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/sim/bd_6f02_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/sim/bd_6f02_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/sim/bd_6f02_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/sim/bd_6f02_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_12/sim/bd_6f02_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/sim/bd_6f02.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1/sim/design_1_axi_smc_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_clk_wiz_299M_0/sim/design_1_rst_clk_wiz_299M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_0/sim/bd_a878_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_1/sim/bd_a878_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_2/sim/bd_a878_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_3/sim/bd_a878_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_4/sim/bd_a878_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_5/sim/bd_a878_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_6/sim/bd_a878_bsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_7/sim/bd_a878_s00mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_8/sim/bd_a878_s00tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_9/sim/bd_a878_s00sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_10/sim/bd_a878_s00a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_11/sim/bd_a878_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_12/sim/bd_a878_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_13/sim/bd_a878_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_14/sim/bd_a878_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_15/sim/bd_a878_sbn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_16/sim/bd_a878_s01mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_17/sim/bd_a878_s01tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_18/sim/bd_a878_s01sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_19/sim/bd_a878_s01a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_20/sim/bd_a878_sarn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_21/sim/bd_a878_srn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_22/sim/bd_a878_sawn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_23/sim/bd_a878_swn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_24/sim/bd_a878_sbn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_25/sim/bd_a878_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_26/sim/bd_a878_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_27/sim/bd_a878_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_28/sim/bd_a878_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_29/sim/bd_a878_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_30/sim/bd_a878_m00bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_31/sim/bd_a878_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/sim/bd_a878.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_0/sim/design_1_axi_smc_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_0/sim/bd_a888_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_1/sim/bd_a888_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_2/sim/bd_a888_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_3/sim/bd_a888_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_4/sim/bd_a888_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_5/sim/bd_a888_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_6/sim/bd_a888_bsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_7/sim/bd_a888_s00mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_8/sim/bd_a888_s00tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_9/sim/bd_a888_s00sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_10/sim/bd_a888_s00a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_11/sim/bd_a888_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_12/sim/bd_a888_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_13/sim/bd_a888_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_14/sim/bd_a888_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_15/sim/bd_a888_sbn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_16/sim/bd_a888_s01mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_17/sim/bd_a888_s01tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_18/sim/bd_a888_s01sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_19/sim/bd_a888_s01a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_20/sim/bd_a888_sarn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_21/sim/bd_a888_srn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_22/sim/bd_a888_sawn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_23/sim/bd_a888_swn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_24/sim/bd_a888_sbn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_25/sim/bd_a888_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_26/sim/bd_a888_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_27/sim/bd_a888_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_28/sim/bd_a888_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_29/sim/bd_a888_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_30/sim/bd_a888_m00bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_31/sim/bd_a888_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/sim/bd_a888.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_0/sim/design_1_axi_smc_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_2/sim/design_1_xbar_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_0/sim/bd_484d_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_1/sim/bd_484d_psr0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_2/sim/bd_484d_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_3/sim/bd_484d_psr_aclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_4/sim/bd_484d_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_5/sim/bd_484d_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_6/sim/bd_484d_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_7/sim/bd_484d_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_8/sim/bd_484d_bsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_9/sim/bd_484d_s00mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_10/sim/bd_484d_s00tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_11/sim/bd_484d_s00sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_12/sim/bd_484d_s00a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_13/sim/bd_484d_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_14/sim/bd_484d_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_15/sim/bd_484d_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_16/sim/bd_484d_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_17/sim/bd_484d_sbn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_18/sim/bd_484d_s01mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_19/sim/bd_484d_s01tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_20/sim/bd_484d_s01sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_21/sim/bd_484d_s01a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_22/sim/bd_484d_sarn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_23/sim/bd_484d_srn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_24/sim/bd_484d_sawn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_25/sim/bd_484d_swn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_26/sim/bd_484d_sbn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_27/sim/bd_484d_s02mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_28/sim/bd_484d_s02tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_29/sim/bd_484d_s02sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_30/sim/bd_484d_s02a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_31/sim/bd_484d_sarn_2.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_32/sim/bd_484d_srn_2.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_33/sim/bd_484d_sawn_2.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_34/sim/bd_484d_swn_2.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_35/sim/bd_484d_sbn_2.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_36/sim/bd_484d_s03mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_37/sim/bd_484d_s03tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_38/sim/bd_484d_s03sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_39/sim/bd_484d_s03a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_40/sim/bd_484d_sarn_3.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_41/sim/bd_484d_srn_3.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_42/sim/bd_484d_sawn_3.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_43/sim/bd_484d_swn_3.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_44/sim/bd_484d_sbn_3.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_45/sim/bd_484d_s04mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_46/sim/bd_484d_s04tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_47/sim/bd_484d_s04sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_48/sim/bd_484d_s04a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_49/sim/bd_484d_sarn_4.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_50/sim/bd_484d_srn_4.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_51/sim/bd_484d_sawn_4.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_52/sim/bd_484d_swn_4.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_53/sim/bd_484d_sbn_4.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_54/sim/bd_484d_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_55/sim/bd_484d_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_56/sim/bd_484d_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_57/sim/bd_484d_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_58/sim/bd_484d_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_59/sim/bd_484d_m00bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_60/sim/bd_484d_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/sim/bd_484d.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_vcu_0_0/sim/design_1_axi_smc_vcu_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_clk_wiz_ctrl_0/sim/design_1_rst_clk_wiz_ctrl_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps8_0_99M_0/sim/design_1_rst_ps8_0_99M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/90c8/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/e893/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/b3c7/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/8cdf/hdl" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/4e49" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_2/sim/design_1_auto_ds_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_2/sim/design_1_auto_pc_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_cc_0/sim/design_1_auto_cc_0.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
