# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.runs/synth_1/design_1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.cache/wt [current_project]
set_property parent.project_path D:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kv260_som:part0:1.3 [current_project]
set_property ip_repo_paths d:/zynqmp_cam_isp_demo/xil_ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib D:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files D:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_mipi_rx_to_video_0_0/hdl/mipi_rx_to_video_v1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_rd_0_0/design_1_v_frmbuf_rd_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_rd_0_0/design_1_v_frmbuf_rd_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_1/design_1_v_frmbuf_wr_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_1/design_1_v_frmbuf_wr_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_xil_vip_0_0/hdl/xil_vip_v1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_xil_isp_lite_0_0/hdl/xil_isp_lite_v1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_xil_vip_0_1/hdl/xil_vip_v1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_2/design_1_v_frmbuf_wr_0_2.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_2/design_1_v_frmbuf_wr_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_0_2/design_1_axis_subset_converter_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frm_wr_0_0/design_1_v_frm_wr_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_v_frm_wr_0_0/design_1_v_frm_wr_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_mipi_rx_to_video_ias1_0/hdl/mipi_rx_to_video_v1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_vcu_0_0/constraints/vcu.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_vcu_0_0/design_1_vcu_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_99M_0/design_1_rst_clk_wiz_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_99M_0/design_1_rst_clk_wiz_99M_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_99M_0/design_1_rst_clk_wiz_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/bd_6f02_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/bd_6f02_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/bd_6f02_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_299M_0/design_1_rst_clk_wiz_299M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_299M_0/design_1_rst_clk_wiz_299M_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_299M_0/design_1_rst_clk_wiz_299M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_1/bd_a878_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_1/bd_a878_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_2/bd_a878_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_3/bd_a878_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_4/bd_a878_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_5/bd_a878_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_6/bd_a878_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_10/bd_a878_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_11/bd_a878_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_12/bd_a878_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_13/bd_a878_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_14/bd_a878_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_15/bd_a878_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_19/bd_a878_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_20/bd_a878_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_21/bd_a878_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_22/bd_a878_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_23/bd_a878_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_24/bd_a878_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_25/bd_a878_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_26/bd_a878_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_27/bd_a878_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_28/bd_a878_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_29/bd_a878_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_30/bd_a878_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_1/bd_a888_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_1/bd_a888_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_2/bd_a888_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_3/bd_a888_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_4/bd_a888_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_5/bd_a888_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_6/bd_a888_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_10/bd_a888_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_11/bd_a888_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_12/bd_a888_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_13/bd_a888_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_14/bd_a888_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_15/bd_a888_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_19/bd_a888_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_20/bd_a888_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_21/bd_a888_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_22/bd_a888_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_23/bd_a888_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_24/bd_a888_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_25/bd_a888_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_26/bd_a888_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_27/bd_a888_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_28/bd_a888_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_29/bd_a888_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_30/bd_a888_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_2_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_xbar_2/design_1_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_1/bd_484d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_1/bd_484d_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_2/bd_484d_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_3/bd_484d_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_4/bd_484d_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_5/bd_484d_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_6/bd_484d_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_10/bd_484d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_11/bd_484d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_12/bd_484d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_13/bd_484d_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_14/bd_484d_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_15/bd_484d_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_19/bd_484d_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_20/bd_484d_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_21/bd_484d_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_22/bd_484d_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_23/bd_484d_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_24/bd_484d_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_28/bd_484d_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_29/bd_484d_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_30/bd_484d_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_31/bd_484d_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_32/bd_484d_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_33/bd_484d_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_37/bd_484d_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_38/bd_484d_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_39/bd_484d_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_40/bd_484d_sawn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_41/bd_484d_swn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_42/bd_484d_sbn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_46/bd_484d_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_47/bd_484d_sarn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_48/bd_484d_srn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_49/bd_484d_sawn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_50/bd_484d_swn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_51/bd_484d_sbn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_52/bd_484d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_53/bd_484d_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_54/bd_484d_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_55/bd_484d_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_56/bd_484d_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/bd_0/ip/ip_57/bd_484d_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_axi_smc_vcu_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_ctrl_0/design_1_rst_clk_wiz_ctrl_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_ctrl_0/design_1_rst_clk_wiz_ctrl_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_ctrl_0/design_1_rst_clk_wiz_ctrl_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.gen/sources_1/bd/design_1/design_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files D:/zynqmp_cam_isp_demo/zynqmp_cam_isp_demo.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
