// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        bytePlanes1_dout,
        bytePlanes1_num_data_valid,
        bytePlanes1_fifo_cap,
        bytePlanes1_empty_n,
        bytePlanes1_read,
        img_din,
        img_num_data_valid,
        img_fifo_cap,
        img_full_n,
        img_write,
        Height_dout,
        Height_num_data_valid,
        Height_fifo_cap,
        Height_empty_n,
        Height_read,
        Width_dout,
        Width_num_data_valid,
        Width_fifo_cap,
        Width_empty_n,
        Width_read,
        WidthInBytes_dout,
        WidthInBytes_num_data_valid,
        WidthInBytes_fifo_cap,
        WidthInBytes_empty_n,
        WidthInBytes_read,
        VideoFormat_dout,
        VideoFormat_num_data_valid,
        VideoFormat_fifo_cap,
        VideoFormat_empty_n,
        VideoFormat_read,
        width_c_din,
        width_c_num_data_valid,
        width_c_fifo_cap,
        width_c_full_n,
        width_c_write,
        height_c_din,
        height_c_num_data_valid,
        height_c_fifo_cap,
        height_c_full_n,
        height_c_write
);

parameter    ap_ST_fsm_state1 = 23'd1;
parameter    ap_ST_fsm_state2 = 23'd2;
parameter    ap_ST_fsm_state3 = 23'd4;
parameter    ap_ST_fsm_state4 = 23'd8;
parameter    ap_ST_fsm_state5 = 23'd16;
parameter    ap_ST_fsm_state6 = 23'd32;
parameter    ap_ST_fsm_state7 = 23'd64;
parameter    ap_ST_fsm_state8 = 23'd128;
parameter    ap_ST_fsm_state9 = 23'd256;
parameter    ap_ST_fsm_state10 = 23'd512;
parameter    ap_ST_fsm_state11 = 23'd1024;
parameter    ap_ST_fsm_state12 = 23'd2048;
parameter    ap_ST_fsm_state13 = 23'd4096;
parameter    ap_ST_fsm_state14 = 23'd8192;
parameter    ap_ST_fsm_state15 = 23'd16384;
parameter    ap_ST_fsm_state16 = 23'd32768;
parameter    ap_ST_fsm_state17 = 23'd65536;
parameter    ap_ST_fsm_state18 = 23'd131072;
parameter    ap_ST_fsm_state19 = 23'd262144;
parameter    ap_ST_fsm_state20 = 23'd524288;
parameter    ap_ST_fsm_state21 = 23'd1048576;
parameter    ap_ST_fsm_state22 = 23'd2097152;
parameter    ap_ST_fsm_state23 = 23'd4194304;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] bytePlanes1_dout;
input  [10:0] bytePlanes1_num_data_valid;
input  [10:0] bytePlanes1_fifo_cap;
input   bytePlanes1_empty_n;
output   bytePlanes1_read;
output  [29:0] img_din;
input  [1:0] img_num_data_valid;
input  [1:0] img_fifo_cap;
input   img_full_n;
output   img_write;
input  [11:0] Height_dout;
input  [1:0] Height_num_data_valid;
input  [1:0] Height_fifo_cap;
input   Height_empty_n;
output   Height_read;
input  [11:0] Width_dout;
input  [2:0] Width_num_data_valid;
input  [2:0] Width_fifo_cap;
input   Width_empty_n;
output   Width_read;
input  [14:0] WidthInBytes_dout;
input  [1:0] WidthInBytes_num_data_valid;
input  [1:0] WidthInBytes_fifo_cap;
input   WidthInBytes_empty_n;
output   WidthInBytes_read;
input  [5:0] VideoFormat_dout;
input  [2:0] VideoFormat_num_data_valid;
input  [2:0] VideoFormat_fifo_cap;
input   VideoFormat_empty_n;
output   VideoFormat_read;
output  [11:0] width_c_din;
input  [1:0] width_c_num_data_valid;
input  [1:0] width_c_fifo_cap;
input   width_c_full_n;
output   width_c_write;
output  [11:0] height_c_din;
input  [1:0] height_c_num_data_valid;
input  [1:0] height_c_fifo_cap;
input   height_c_full_n;
output   height_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg bytePlanes1_read;
reg[29:0] img_din;
reg img_write;
reg Height_read;
reg Width_read;
reg WidthInBytes_read;
reg VideoFormat_read;
reg width_c_write;
reg height_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Height_blk_n;
reg    Width_blk_n;
reg    WidthInBytes_blk_n;
reg    VideoFormat_blk_n;
reg    width_c_blk_n;
reg    height_c_blk_n;
reg   [14:0] widthInPix_reg_496;
wire   [5:0] VideoFormat_read_read_fu_184_p2;
reg   [5:0] VideoFormat_read_reg_503;
reg   [11:0] Height_read_reg_507;
reg   [11:0] Width_read_reg_513;
reg   [12:0] trunc_ln_reg_525;
wire    ap_CS_fsm_state2;
wire   [2:0] grp_fu_271_p2;
reg   [2:0] remainPix_2_reg_531;
wire    ap_CS_fsm_state17;
wire   [0:0] icmp_ln1292_fu_284_p2;
reg   [0:0] icmp_ln1292_reg_536;
wire    ap_CS_fsm_state18;
wire   [12:0] sub222_fu_298_p2;
reg   [12:0] sub222_reg_541;
wire   [0:0] cmp226_fu_303_p2;
reg   [0:0] cmp226_reg_546;
wire   [0:0] icmp16_fu_319_p2;
reg   [0:0] icmp16_reg_551;
wire   [0:0] cmp226_2_fu_325_p2;
reg   [0:0] cmp226_2_reg_556;
reg   [0:0] tmp_3_reg_561;
wire   [0:0] cmp226_4_fu_339_p2;
reg   [0:0] cmp226_4_reg_566;
wire   [12:0] trunc_ln1249_1_fu_376_p4;
reg   [12:0] trunc_ln1249_1_reg_581;
wire    ap_CS_fsm_state21;
wire   [0:0] icmp_ln1252_fu_390_p2;
reg   [0:0] icmp_ln1252_reg_586;
wire   [12:0] sub121_fu_404_p2;
reg   [12:0] sub121_reg_591;
wire   [0:0] cmp125_fu_410_p2;
reg   [0:0] cmp125_reg_596;
wire   [0:0] icmp_fu_426_p2;
reg   [0:0] icmp_reg_601;
wire   [0:0] cmp125_2_fu_432_p2;
reg   [0:0] cmp125_2_reg_606;
wire   [0:0] icmp13_fu_448_p2;
reg   [0:0] icmp13_reg_611;
wire   [0:0] cmp125_4_fu_454_p2;
reg   [0:0] cmp125_4_reg_616;
wire   [0:0] cmp125_5_fu_460_p2;
reg   [0:0] cmp125_5_reg_621;
wire   [0:0] cmp125_6_fu_466_p2;
reg   [0:0] cmp125_6_reg_626;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_start;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_done;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_idle;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_ready;
wire   [29:0] grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_img_din;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_img_write;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_bytePlanes1_read;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_start;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_done;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_idle;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_ready;
wire   [29:0] grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_img_din;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_img_write;
wire    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_bytePlanes1_read;
reg    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_start_reg;
wire    ap_CS_fsm_state19;
wire   [0:0] icmp_ln1295_fu_348_p2;
wire    ap_CS_fsm_state20;
reg    grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_start_reg;
wire    ap_CS_fsm_state22;
wire   [0:0] icmp_ln1255_fu_480_p2;
wire    ap_CS_fsm_state23;
reg   [11:0] y_1_fu_170;
wire   [11:0] y_5_fu_353_p2;
reg   [11:0] y_fu_174;
wire   [11:0] y_3_fu_485_p2;
reg    ap_block_state1;
wire   [15:0] zext_ln1289_fu_252_p1;
wire   [15:0] add_ln1289_fu_255_p2;
wire   [3:0] grp_fu_271_p1;
wire   [2:0] trunc_ln1291_fu_281_p1;
wire   [2:0] remainPix_3_fu_290_p3;
wire   [1:0] tmp_2_fu_309_p4;
wire   [15:0] zext_ln1249_fu_367_p1;
wire   [15:0] add_ln1249_fu_370_p2;
wire   [2:0] remainPix_fu_364_p1;
wire   [3:0] zext_ln1251_fu_386_p1;
wire   [3:0] remainPix_1_fu_396_p3;
wire   [2:0] tmp_fu_416_p4;
wire   [1:0] tmp_1_fu_438_p4;
reg    grp_fu_271_ap_start;
wire    grp_fu_271_ap_done;
reg   [22:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 23'd1;
#0 widthInPix_reg_496 = 15'd0;
#0 VideoFormat_read_reg_503 = 6'd0;
#0 Height_read_reg_507 = 12'd0;
#0 Width_read_reg_513 = 12'd0;
#0 trunc_ln_reg_525 = 13'd0;
#0 remainPix_2_reg_531 = 3'd0;
#0 icmp_ln1292_reg_536 = 1'd0;
#0 sub222_reg_541 = 13'd0;
#0 cmp226_reg_546 = 1'd0;
#0 icmp16_reg_551 = 1'd0;
#0 cmp226_2_reg_556 = 1'd0;
#0 tmp_3_reg_561 = 1'd0;
#0 cmp226_4_reg_566 = 1'd0;
#0 trunc_ln1249_1_reg_581 = 13'd0;
#0 icmp_ln1252_reg_586 = 1'd0;
#0 sub121_reg_591 = 13'd0;
#0 cmp125_reg_596 = 1'd0;
#0 icmp_reg_601 = 1'd0;
#0 cmp125_2_reg_606 = 1'd0;
#0 icmp13_reg_611 = 1'd0;
#0 cmp125_4_reg_616 = 1'd0;
#0 cmp125_5_reg_621 = 1'd0;
#0 cmp125_6_reg_626 = 1'd0;
#0 grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_start_reg = 1'b0;
#0 grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_start_reg = 1'b0;
#0 y_1_fu_170 = 12'd0;
#0 y_fu_174 = 12'd0;
end

design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4 grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_start),
    .ap_done(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_done),
    .ap_idle(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_idle),
    .ap_ready(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_ready),
    .img_din(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_img_din),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_full_n(img_full_n),
    .img_write(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_img_write),
    .trunc_ln(trunc_ln_reg_525),
    .icmp_ln1292(icmp_ln1292_reg_536),
    .cmp226_4(cmp226_4_reg_566),
    .cmp226_3(tmp_3_reg_561),
    .cmp226_2(cmp226_2_reg_556),
    .cmp226_1(icmp16_reg_551),
    .bytePlanes1_dout(bytePlanes1_dout),
    .bytePlanes1_num_data_valid(11'd0),
    .bytePlanes1_fifo_cap(11'd0),
    .bytePlanes1_empty_n(bytePlanes1_empty_n),
    .bytePlanes1_read(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_bytePlanes1_read),
    .sub222_cast17(sub222_reg_541),
    .cmp226(cmp226_reg_546)
);

design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1 grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_start),
    .ap_done(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_done),
    .ap_idle(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_idle),
    .ap_ready(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_ready),
    .img_din(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_img_din),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_full_n(img_full_n),
    .img_write(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_img_write),
    .trunc_ln1249_1(trunc_ln1249_1_reg_581),
    .icmp_ln1252(icmp_ln1252_reg_586),
    .cmp125_6(cmp125_6_reg_626),
    .cmp125_5(cmp125_5_reg_621),
    .cmp125_4(cmp125_4_reg_616),
    .cmp125_3(icmp13_reg_611),
    .cmp125_2(cmp125_2_reg_606),
    .cmp125_1(icmp_reg_601),
    .bytePlanes1_dout(bytePlanes1_dout),
    .bytePlanes1_num_data_valid(11'd0),
    .bytePlanes1_fifo_cap(11'd0),
    .bytePlanes1_empty_n(bytePlanes1_empty_n),
    .bytePlanes1_read(grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_bytePlanes1_read),
    .sub121_cast16(sub121_reg_591),
    .cmp125(cmp125_reg_596)
);

design_1_v_frmbuf_rd_0_0_urem_12ns_4ns_3_16_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
urem_12ns_4ns_3_16_seq_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_271_ap_start),
    .done(grp_fu_271_ap_done),
    .din0(Width_read_reg_513),
    .din1(grp_fu_271_p1),
    .ce(1'b1),
    .dout(grp_fu_271_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Height_read_reg_507 <= 12'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            Height_read_reg_507 <= Height_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        VideoFormat_read_reg_503 <= 6'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            VideoFormat_read_reg_503 <= VideoFormat_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        Width_read_reg_513 <= 12'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            Width_read_reg_513 <= Width_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state19) & (~(6'd25 == VideoFormat_read_reg_503) | (icmp_ln1295_fu_348_p2 == 1'd1)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cmp125_2_reg_606 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            cmp125_2_reg_606 <= cmp125_2_fu_432_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cmp125_4_reg_616 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            cmp125_4_reg_616 <= cmp125_4_fu_454_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cmp125_5_reg_621 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            cmp125_5_reg_621 <= cmp125_5_fu_460_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cmp125_6_reg_626 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            cmp125_6_reg_626 <= cmp125_6_fu_466_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cmp125_reg_596 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            cmp125_reg_596 <= cmp125_fu_410_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cmp226_2_reg_556 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            cmp226_2_reg_556 <= cmp226_2_fu_325_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cmp226_4_reg_566 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            cmp226_4_reg_566 <= cmp226_4_fu_339_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        cmp226_reg_546 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            cmp226_reg_546 <= cmp226_fu_303_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1255_fu_480_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
            grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_start_reg <= 1'b1;
        end else if ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_ready == 1'b1)) begin
            grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1295_fu_348_p2 == 1'd0) & (6'd25 == VideoFormat_read_reg_503) & (1'b1 == ap_CS_fsm_state19))) begin
            grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_start_reg <= 1'b1;
        end else if ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_ready == 1'b1)) begin
            grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp13_reg_611 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            icmp13_reg_611 <= icmp13_fu_448_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp16_reg_551 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            icmp16_reg_551 <= icmp16_fu_319_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1252_reg_586 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            icmp_ln1252_reg_586 <= icmp_ln1252_fu_390_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_ln1292_reg_536 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            icmp_ln1292_reg_536 <= icmp_ln1292_fu_284_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        icmp_reg_601 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            icmp_reg_601 <= icmp_fu_426_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        remainPix_2_reg_531 <= 3'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            remainPix_2_reg_531 <= grp_fu_271_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sub121_reg_591 <= 13'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            sub121_reg_591 <= sub121_fu_404_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sub222_reg_541 <= 13'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            sub222_reg_541 <= sub222_fu_298_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        tmp_3_reg_561 <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            tmp_3_reg_561 <= remainPix_3_fu_290_p3[32'd2];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln1249_1_reg_581 <= 13'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            trunc_ln1249_1_reg_581 <= {{add_ln1249_fu_370_p2[15:3]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        trunc_ln_reg_525 <= 13'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            trunc_ln_reg_525 <= {{add_ln1289_fu_255_p2[15:3]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        widthInPix_reg_496 <= 15'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            widthInPix_reg_496 <= WidthInBytes_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        y_1_fu_170 <= 12'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            y_1_fu_170 <= 12'd0;
        end else if (((icmp_ln1295_fu_348_p2 == 1'd0) & (6'd25 == VideoFormat_read_reg_503) & (1'b1 == ap_CS_fsm_state19))) begin
            y_1_fu_170 <= y_5_fu_353_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        y_fu_174 <= 12'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            y_fu_174 <= 12'd0;
        end else if (((icmp_ln1255_fu_480_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
            y_fu_174 <= y_3_fu_485_p2;
        end
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_blk_n = VideoFormat_empty_n;
    end else begin
        VideoFormat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_read = 1'b1;
    end else begin
        VideoFormat_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_blk_n = WidthInBytes_empty_n;
    end else begin
        WidthInBytes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_read = 1'b1;
    end else begin
        WidthInBytes_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Width_blk_n = Width_empty_n;
    end else begin
        Width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Width_read = 1'b1;
    end else begin
        Width_read = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_done == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (~(6'd25 == VideoFormat_read_reg_503) | (icmp_ln1295_fu_348_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (~(6'd25 == VideoFormat_read_reg_503) | (icmp_ln1295_fu_348_p2 == 1'd1)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        bytePlanes1_read = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_bytePlanes1_read;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        bytePlanes1_read = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_bytePlanes1_read;
    end else begin
        bytePlanes1_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_271_ap_start = 1'b1;
    end else begin
        grp_fu_271_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_blk_n = height_c_full_n;
    end else begin
        height_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_write = 1'b1;
    end else begin
        height_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        img_din = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_img_din;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        img_din = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_img_din;
    end else begin
        img_din = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_img_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        img_write = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_img_write;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        img_write = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_img_write;
    end else begin
        img_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_c_blk_n = width_c_full_n;
    end else begin
        width_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_c_write = 1'b1;
    end else begin
        width_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (6'd24 == VideoFormat_read_read_fu_184_p2) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else if ((~(6'd24 == VideoFormat_read_read_fu_184_p2) & ~(6'd25 == VideoFormat_read_read_fu_184_p2) & ~((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else if ((~((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (6'd25 == VideoFormat_read_read_fu_184_p2) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((1'b1 == ap_CS_fsm_state19) & (~(6'd25 == VideoFormat_read_reg_503) | (icmp_ln1295_fu_348_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((icmp_ln1255_fu_480_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((1'b1 == ap_CS_fsm_state23) & (grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign VideoFormat_read_read_fu_184_p2 = VideoFormat_dout;

assign add_ln1249_fu_370_p2 = (zext_ln1249_fu_367_p1 + 16'd7);

assign add_ln1289_fu_255_p2 = (zext_ln1289_fu_252_p1 + 16'd7);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

always @ (*) begin
    ap_block_state1 = ((height_c_full_n == 1'b0) | (width_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0));
end

assign cmp125_2_fu_432_p2 = ((remainPix_1_fu_396_p3 > 4'd2) ? 1'b1 : 1'b0);

assign cmp125_4_fu_454_p2 = ((remainPix_1_fu_396_p3 > 4'd4) ? 1'b1 : 1'b0);

assign cmp125_5_fu_460_p2 = ((remainPix_1_fu_396_p3 > 4'd5) ? 1'b1 : 1'b0);

assign cmp125_6_fu_466_p2 = ((remainPix_1_fu_396_p3 > 4'd6) ? 1'b1 : 1'b0);

assign cmp125_fu_410_p2 = ((remainPix_1_fu_396_p3 != 4'd0) ? 1'b1 : 1'b0);

assign cmp226_2_fu_325_p2 = ((remainPix_3_fu_290_p3 > 3'd2) ? 1'b1 : 1'b0);

assign cmp226_4_fu_339_p2 = ((remainPix_3_fu_290_p3 > 3'd4) ? 1'b1 : 1'b0);

assign cmp226_fu_303_p2 = ((remainPix_3_fu_290_p3 != 3'd0) ? 1'b1 : 1'b0);

assign grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_start = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1262_1_fu_234_ap_start_reg;

assign grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_start = grp_Bytes2MultiPixStream_Pipeline_VITIS_LOOP_1302_4_fu_218_ap_start_reg;

assign grp_fu_271_p1 = 12'd6;

assign height_c_din = Height_dout;

assign icmp13_fu_448_p2 = ((tmp_1_fu_438_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp16_fu_319_p2 = ((tmp_2_fu_309_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_fu_426_p2 = ((tmp_fu_416_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1252_fu_390_p2 = ((remainPix_fu_364_p1 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1255_fu_480_p2 = ((y_fu_174 == Height_read_reg_507) ? 1'b1 : 1'b0);

assign icmp_ln1292_fu_284_p2 = ((trunc_ln1291_fu_281_p1 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1295_fu_348_p2 = ((y_1_fu_170 == Height_read_reg_507) ? 1'b1 : 1'b0);

assign remainPix_1_fu_396_p3 = ((icmp_ln1252_fu_390_p2[0:0] == 1'b1) ? 4'd8 : zext_ln1251_fu_386_p1);

assign remainPix_3_fu_290_p3 = ((icmp_ln1292_fu_284_p2[0:0] == 1'b1) ? 3'd6 : trunc_ln1291_fu_281_p1);

assign remainPix_fu_364_p1 = widthInPix_reg_496[2:0];

assign sub121_fu_404_p2 = ($signed(trunc_ln1249_1_fu_376_p4) + $signed(13'd8191));

assign sub222_fu_298_p2 = ($signed(trunc_ln_reg_525) + $signed(13'd8191));

assign tmp_1_fu_438_p4 = {{remainPix_1_fu_396_p3[3:2]}};

assign tmp_2_fu_309_p4 = {{remainPix_3_fu_290_p3[2:1]}};

assign tmp_fu_416_p4 = {{remainPix_1_fu_396_p3[3:1]}};

assign trunc_ln1249_1_fu_376_p4 = {{add_ln1249_fu_370_p2[15:3]}};

assign trunc_ln1291_fu_281_p1 = remainPix_2_reg_531[2:0];

assign width_c_din = Width_dout;

assign y_3_fu_485_p2 = (y_fu_174 + 12'd1);

assign y_5_fu_353_p2 = (y_1_fu_170 + 12'd1);

assign zext_ln1249_fu_367_p1 = widthInPix_reg_496;

assign zext_ln1251_fu_386_p1 = remainPix_fu_364_p1;

assign zext_ln1289_fu_252_p1 = widthInPix_reg_496;

endmodule //design_1_v_frmbuf_rd_0_0_Bytes2MultiPixStream
